# Site settings
title: "Farman Shah"
description: "Professional resume of Farman Shah."
timezone: "Asia/Karachi"
future: true

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Farman Shah"
resume_title:                   |
  <div>
    Software Research & Development Manager
  </div>
resume_contact_email:           "farman.a.shah@gmail.com"
resume_header_contact_info:     "farman.a.shah@gmail.com"
resume_header_contact_phone:     "+92 333 726 6745"
resume_header_intro:            |
  <p>
    Helping large-scale enterprises with high-quality software solutions since 2012, I specialize in leading agile development teams to build scalable, reliable, and innovative software. With a strong background in Scrum methodologies, software architecture, and AI-driven technologies, I focus on optimizing development workflows, enhancing product stability, and aligning engineering efforts with business goals. Passionate about mentoring teams, driving innovation, and delivering impactful solutions, I thrive in dynamic environments where technology meets business excellence.
  </p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_technologies:    true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
resume_section_independent:     true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/"
  # resume_twitter_url:           "http://twitter.com/"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://pk.linkedin.com/in/syedfarmanalishah"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
